export const NFT_COLUMN_COUNT = "NFT_COLUMN_COUNT"
export const UI_ERROR = "UI_ERROR"

export const FILTER_STATUS            = "FILTER_STATUS"
export const FILTER_STATUS_BUY_NOW    = 0
export const FILTER_STATUS_ON_AUCTION = 1
export const FILTER_STATUS_NEW        = 2
export const FILTER_STATUS_HAS_OFFERS = 3
export let FILTER_STATUS_TXT = []
FILTER_STATUS_TXT[FILTER_STATUS_BUY_NOW]    = "Buy Now"
FILTER_STATUS_TXT[FILTER_STATUS_ON_AUCTION] = "On Auction"
FILTER_STATUS_TXT[FILTER_STATUS_NEW]        = "New"
FILTER_STATUS_TXT[FILTER_STATUS_HAS_OFFERS] = "Has Offers"

